// install the "REST Client" extension in VSCode.
@baseUrl=localhost:3000

###

# add new order for double espresso
POST http://{{baseUrl}}/coffeeorders HTTP/1.1
content-type: application/json

{
    "coffee": "triple espresso",
    "emailAddress": "audstanley@gmail.com",
    "flavor": "pumpkin spice",
    "strength": "100"
}

###

# add new order for espresso
POST http://{{baseUrl}}/coffeeorders HTTP/1.1
content-type: application/json

{
    "coffee": "espresso",
    "emailAddress": "aeinstein@aol.com",
    "flavor": "mocha",
    "strength": "80"
}

###

# add new order for americano
POST http://{{baseUrl}}/coffeeorders HTTP/1.1
content-type: application/json

{
    "coffee": "americano",
    "emailAddress": "sjobs@apple.com",
    "flavor": "caramel",
    "size": "grande",
    "strength": "60"
}

###

# add new order for earl grey
POST http://{{baseUrl}}/coffeeorders HTTP/1.1
content-type: application/json

{
    "coffee": "earl grey",
    "emailAddress": "jlpicard@starfleet.com",
    "flavor": "none",
    "size": "tall",
    "strength": "80"
}

###
